// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FhhWyGjuO1kieZYdG6iD44S4YlJ-QJw',
    appId: '1:646892833201:web:12a5d7e6cfbe5714e49590',
    messagingSenderId: '646892833201',
    projectId: 'do-it-e5662',
    authDomain: 'do-it-e5662.firebaseapp.com',
    storageBucket: 'do-it-e5662.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-YcKHevGigp7ub-XsboJlwl4Ci0T-Kt4',
    appId: '1:646892833201:android:647d05020deb040ee49590',
    messagingSenderId: '646892833201',
    projectId: 'do-it-e5662',
    storageBucket: 'do-it-e5662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOrDq4k6cKR6oOIEbObIpppnKS0PpYCw',
    appId: '1:646892833201:ios:7b51f8852270ac75e49590',
    messagingSenderId: '646892833201',
    projectId: 'do-it-e5662',
    storageBucket: 'do-it-e5662.firebasestorage.app',
    iosClientId: '646892833201-9h53d7vpiu9dq1g2nc7hut0ctkob39sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.doIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOrDq4k6cKR6oOIEbObIpppnKS0PpYCw',
    appId: '1:646892833201:ios:7b51f8852270ac75e49590',
    messagingSenderId: '646892833201',
    projectId: 'do-it-e5662',
    storageBucket: 'do-it-e5662.firebasestorage.app',
    iosClientId: '646892833201-9h53d7vpiu9dq1g2nc7hut0ctkob39sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.doIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-FhhWyGjuO1kieZYdG6iD44S4YlJ-QJw',
    appId: '1:646892833201:web:12a5d7e6cfbe5714e49590',
    messagingSenderId: '646892833201',
    projectId: 'do-it-e5662',
    authDomain: 'do-it-e5662.firebaseapp.com',
    storageBucket: 'do-it-e5662.firebasestorage.app',
  );

}